CREATE FUNCTION ufn_GetSalaryLevel(@salary DECIMAL(18,4))
RETURNS VARCHAR(10)
	BEGIN
		IF @salary < 30000
		RETURN 'Low'
		ELSE IF @salary BETWEEN 30000 AND 50000
		RETURN 'Average'
		ELSE
		RETURN 'High'

		RETURN NULL
	END